# Site settings
title: Byte-Size Snacks
email: maks@kolman.si
description: >- # this means to ignore newlines until "baseurl:"
    A site to hold my thoughts, code, experiments and tools.
    I will keep fixing it until it's completely broken.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.kolman.si"

# Show descriptions on the first page
show_excerpts: yes

# Media IDs
github_username:  MKolman
linkedin_username: MaksKolman
youtube_username: KolmanMaks
google_analytics: UA-42885055-4
google_site_verification: 9ZiZUK7dkw6zLRwMYV8LNIdwcvbseiUhwVsfl8n3k-0
google_adsense: ca-pub-7785253471931691

# Blog posts URL format
permalink: /blog/:title/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
