#!/usr/bin/env bash
set -e  # halt script on error

bundle exec jekyll build
bundle exec htmlproofer ./_site --ignore-urls "/dm.kolman.si/,/www.ijs.si/,/www.linkedin.com/in/MaksKolman/,/www.uni-lj.si/" --disable-external true 
